---
Name: silverstripe-sentry
---

phptek\Sentry\Adaptor\RavenClient:
  install: true

SilverStripe\Core\Injector\Injector:
  Logger:
    calls:
      - [ pushHandler, [ %$SentryHandler ]] 
  SentryHandler:
    class: phptek\Sentry\SentryHandler
    constructor:
      client: %$phptek\Sentry\Adaptor\RavenClient
      config: []
    properties:
      formatter: %$Monolog\Formatter\JsonFormatter
    
