---
Name: silverstripe-sentry
---

phptek\Sentry\Adaptor\RavenClient:
  install: true

SilverStripe\Core\Injector\Injector:
  Logger:
    calls:
      # Try popHandler to lose the defaukt SS4 handler?
      SentryHandler: [pushHandler, [ %$SentryHandler ]] 
  SentryHandler:
    class: phptek\Sentry\SentryHandler
    constructor:
      client: %$phptek\Sentry\Adaptor\RavenClient
    properties:
      Formatter: %$SentryLogFormatter
  SentryLogFormatter:
    class: phptek\Sentry\SentryLogFormatter
    
